version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER= alp
      - POSTGRES_PASSWORD= alp
      - POSTGRES_DB= alp-bank-DB
    ports:
      - '5432:5432'